language: node_js

node_js:
  - 10

notifications:
  email: false

cache: yarn

install: 
- yarn intall

script:
 - yarn test
 - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master