language: node_js

node_js:
  - 10

notifications:
  email: false

cache: npm

install: 
- npm intall

script:
 - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master